defaults:
  - train
  - _self_

batch_size: 8192

mesh:
  _target_: pinnstf2.data.PointCloud
  root_dir: ${paths.data_dir}
  read_data_fn: ???

train_datasets:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      solution:
        - c

  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      collection_points:
        - e1
        - e2
        - e3
        - e4
        - e5
      use_lhs: false

val_dataset:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      idx_t: 100
      solution:
        - c
        - u
        - v
        - w
        - p

test_dataset:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      idx_t: 100
      solution:
        - c
        - u
        - v
        - w
        - p

net:
  _target_: pinnstf2.models.NetHFM
  layers: [4, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 5]
  output_names:
    - c
    - u
    - v
    - w
    - p

model:
  loss_fn: mse

trainer:
  accelerator: gpu
  max_epochs: 10000
  check_val_every_n_epoch: 100

train: true
test: false
val: true

optimized_metric:
  error:
    - c
    - u
    - v
    - w
    - p

task_name: aneurysm3D

hydra:
  searchpath:
    - pkg://pinnstf2/conf